#%RAML 0.8
title: Hotel API
version: v1
baseUri: http://api.samplehost.com

/bookings:
  get:
    queryParameters:
      customerId:
        displayName: Customer ID
        type: string
        required: false
      roomId:
        displayName: Room ID
        type: string
        required: false
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "array",
                "items": {
                  "$ref": "#/definitions/booking"
                },
                "definitions": {
                  "booking": {
                    "type": "object",
                    "properties": {
                      "roomId": {
                        "type": "string"
                      },
                      "customerId": {
                        "type": "string"
                      },
                      "fromDate": {
                        "javaType":"java.time.LocalDate"
                      },
                      "toDate": {
                        "javaType":"java.time.LocalDate"
                      }
                    },
                    "required": [
                      "roomId",
                      "customerId",
                      "fromDate",
                      "toDate"
                    ],
                    "additionalProperties": false
                  }
                }
              }
  post:
    body:
      application/json:
        schema: |
            {
               "$schema": "http://json-schema.org/draft-04/schema#",
               "type": "object",
               "properties":{
                  "roomId":{
                     "type":"string"
                  },
                  "customerId":{
                     "type":"string"
                  },
                  "fromDate":{
                     "javaType":"java.time.LocalDate"
                  },
                  "toDate":{
                     "javaType":"java.time.LocalDate"
                  }
               }
            }
    responses:
      200:
        body:
         application/json:
          schema: |
            {
               "$schema": "http://json-schema.org/draft-04/schema#",
               "type": "object",
               "properties":{
                  "message":{
                     "type":"string"
                  }
               }
            }
/availability:
  /{roomId}:
    uriParameters:
      roomId:
        displayName: Room ID
        type: string
    get:
      queryParameters:
        fromDate:
          type: string
          required: false
        toDate:
          type: string
          required: false
      responses:
            200:
              body:
                application/json:
                  schema: |
                    {
                      "$schema": "http://json-schema.org/draft-04/schema#",
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/availability"
                      },
                      "definitions": {
                        "availability": {
                          "type": "object",
                          "properties": {
                            "roomId": {
                              "type": "string"
                            },
                            "availability": {
                               "enum": [ "booked", "available" ]
                            },
                            "date": {
                              "javaType":"java.time.LocalDate"
                            }
                          },
                          "required": [
                            "roomId",
                            "customerId",
                            "fromDate",
                            "toDate"
                          ],
                          "additionalProperties": false
                        }
                      }
                    }

